name: beso
channels:
  - conda-forge
dependencies:
  - matplotlib=3.3.1=1
  - numpy=1.19.1=py38hbc27379_2

  # Dev Dependencies
  # ----------------
  - autopep8=1.5.4=pyh9f0ad1d_0
  - rope=0.17.0
  
  # Test dependencies
  - pytest=6.0.1
  - pytest-cov=2.10.1
  - coverage=5.2.1
  - coveralls=2.1.2
